{% set name = "cloupy" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cloupy-{{ version }}.tar.gz
  sha256: e6281daddaeb05a62b001b12d823101a9b985508858d357705a7537cf7942021

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pandas >=1.3.3,<=1.3.5
    - matplotlib-base >=3.4.3,<=3.5.1
    - requests >=2.26.0,<=2.27.1
    - beautifulsoup4 >=4.9.3,<=4.10.0
    - numpy >=1.21.4,<=1.22.1
    - pyshp ==2.1.3
    - pyproj >=3.2.1,<=3.3.0
    - scipy >=1.7.2,<=1.7.3
    - pillow >=8.4.0,<=9.0.0
    - cycler ==0.11.0

test:
  imports:
    - cloupy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pdGruby/cloupy
  summary: The package allows to download, process and visualize climatological data from reliable sources
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mfansler
